version: '3.9'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'
    links: 
      - server  
     